[project]
name = "merchants-sdk"
version = "2026.3.1"
description = "Payments for people who have better things to do."
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.10"
dependencies = ["pydantic>=2.13.3", "requests>=2.33.1"]

[project.optional-dependencies]
flow = ["pyflowcl>=2026.3.0"]
khipu = ["khipu-tools>=2025.1.0"]
cli = ["typer>=0.24.1"]
sqlalchemy = ["sqlalchemy>=2.0.49"]
dev = [
    "pytest>=9.0.3",
    "pytest-cov",
    "ruff",
    "responses>=0.26.0",
    "typer>=0.24.1",
    "sqlalchemy>=2.0.49",
    "pre-commit",
    "mkdocs>=1.6.1",
    "mkdocs-material>=9.7.6",
    "mkdocstrings[python]>=1.0.4",
]

[project.urls]
homepage = "https://github.com/mariofix/merchants/"
repository = "https://github.com/mariofix/merchants/"
documentation = "https://mariofix.github.io/merchants/"


[tool.poetry]
packages = [{ include = "merchants" }]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[project.scripts]
merchants = "merchants.cli:app"


[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = "-v"

[tool.ruff]
line-length = 119
target-version = "py310"

[tool.ruff.lint]
select = ["E", "F", "I", "UP"]
