[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "merchants"
version = "2024.9.16"
description = "A unified payment processing toolkit for Starlette/FastAPI applications"
authors = [{ name = "Mario Hernandez", email = "mariofix@proton.me" }]
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.10"
keywords = [
    "payment",
    "psp",
    "payment-gateway",
    "payment-integration",
    "payment-processing",
    "payment-hub",
    "payment-platform",
    "fastapi",
    "starlette",
]
classifiers = [
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
dependencies = [
    "thankyou>=0.0.3",
    "pendulum>=3.0.0",
    "httpx>=0.27.0",
    "python-slugify>=8.0.4",
    "alembic>=1.13.2",
    "sqlalchemy>=2.0.35",
    "sqlalchemy-utils>=0.41.2",
    "fastapi[all]>=0.114.2",
    "starlette-admin>=0.14.1",
]

[project.optional-dependencies]
dev = [
    "pytest>=8.3.3",
    "coverage>=7.6.1",
    "black>=24.8.0",
    "pre-commit>=3.8.0",
    "rich>=13.7.1",
    "pytest-asyncio>=0.24.0",
]

[project.urls]
Homepage = "https://mariofix.github.io/merchants"
Repository = "https://github.com/mariofix/merchants"

[tool.hatch.build.targets.wheel]
packages = ["merchants", "alembic"]


[tool.pytest.ini_options]
addopts = "-ra"
testpaths = ["tests"]
python_files = ["test*.py"]


[tool.black]
line-length = 119
target-version = ['py310']
include = '\.pyi?$'

[tool.ruff]
line-length = 119
target-version = "py310"

[tool.bandit]
exclude_dirs = ["tests"]
skips = ["B101", "B601"]
